version: 2

before:
  hooks:
    - go mod tidy -diff
    - go mod download
    - go mod verify

builds:
  - main: ./cmd/vipdatasync
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.fullCommit={{ .FullCommit }} -X main.commitDate={{ .CommitDate }} -X main.gitTreeState={{ .IsGitDirty }} -X main.builtBy=goreleaser

gomod:
  proxy: true
  env:
    - GOPROXY=https://proxy.golang.org
    - GOSUMDB=sum.golang.org

changelog:
  disable: true
