# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

before:
  hooks:
    - go mod tidy -diff
    - go mod download
    - go mod verify

builds:
  - main: ./cmd/vipdatasync
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.fullCommit={{ .FullCommit }} -X main.commitDate={{ .CommitDate }} -X main.gitTreeState={{ .IsGitDirty }} -X main.builtBy=goreleaser

gomod:
  proxy: true
  env:
    - GOPROXY=https://proxy.golang.org
    - GOSUMDB=sum.golang.org

changelog:
  disable: true

brews:
  - name: vipdatasync
    commit_author:
      name: tangrufusbot
      email: 39258755+tangrufusbot@users.noreply.github.com
    directory: Formula
    homepage: "https://github.com/typisttech/vipdatasync"
    description: "CLI utility for WordPress VIP data sync management"
    license: MIT
    skip_upload: auto

    # Custom block for brew.
    # Can be used to specify alternate downloads for devel or head releases.
    custom_block: |
      head do 
        "https://github.com/typisttech/vipdatasync", branch: "main"
        depends_on "pkg-config" => :build
      end

    # TODO!
    test: |
      system "#{bin}/vipdatasync" "--version222"

    repository:
      owner: typisttech
      name: homebrew-vipdatasync
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
      branch: goreleaser
      pull_request:
        enabled: true
