# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

before:
  hooks:
    - go mod tidy -diff
    - go mod download
    - go mod verify

builds:
  - main: ./cmd/vipdatasync
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.fullCommit={{ .FullCommit }} -X main.commitDate={{ .CommitDate }} -X main.gitTreeState={{ .IsGitDirty }} -X main.builtBy=goreleaser

gomod:
  proxy: true
  env:
    - GOPROXY=https://proxy.golang.org
    - GOSUMDB=sum.golang.org

changelog:
  disable: true

brews:
  - name: vipdatasync
    commit_author:
      name: tangrufusbot
      email: 39258755+tangrufusbot@users.noreply.github.com
    directory: Formula
    homepage: "https://github.com/typisttech/vipdatasync"
    description: "CLI utility for WordPress VIP data sync management"
    license: MIT
    skip_upload: auto
    custom_block: |
      # rubocop:disable FormulaAudit/ComponentsOrder,Style/DisableCopsWithinSourceCodeDirective
      head do
        url "https://github.com/typisttech/vipdatasync.git", branch: "main"
        depends_on "go" => :build
      end
      # rubocop:enable FormulaAudit/ComponentsOrder,Style/DisableCopsWithinSourceCodeDirective
    test: |
      system "#{bin}/vipdatasync", "--version345"
    install: |
      if build.head?
        system "go", "build", "-o", "dist/vipdatasync", "./cmd/vipdatasync"
        bin.install "dist/vipdatasync"
      else
        bin.install "vipdatasync"
      end
    repository:
      owner: typisttech
      name: homebrew-vipdatasync
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
      branch: goreleaser
      pull_request:
        enabled: true
