name: Release

on:
  push:
    tags:
      - 'v*'

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      build-provenance-artifact: build-provenance
      sbom-attestations: ${{ steps.upload-sbom.outputs.attestations }}
      sbom-artifact: ${{ steps.upload-sbom.outputs.artifact }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - uses: anchore/sbom-action/download-syft@v0
      - uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: build-provenance
          compression-level: 0
          path: |
            dist/vipdatasync_*/vipdatasync
            dist/vipdatasync_*.tar.gz
            dist/**/*.sbom.json
      - uses: typisttech/tmp-attest-goreleaser-sbom-action@main
        id: upload-sbom

  attest-build-provenance:
    needs: [release]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ needs.release.outputs.build-provenance-artifact }}
      - uses: actions/attest-build-provenance@v1
        with:
          subject-path: |
            vipdatasync_*/vipdatasync
            vipdatasync_*.tar.gz
            **/*.sbom.json

  attest-sbom:
    needs: [release]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
    strategy:
      matrix:
        attestation: ${{ fromJSON(needs.release.outputs.sbom-attestations) }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ needs.release.outputs.sbom-artifact }}
      - uses: actions/attest-sbom@v1
        with:
          subject-path: ${{ matrix.attestation.subject }}
          sbom-path: ${{ matrix.attestation.sbom }}

  verify-attestation:
    needs: [release, attest-build-provenance, attest-sbom]
    runs-on: ubuntu-latest
    steps:
      - run: rm -dfr artifacts
      - run: gh release download --clobber --dir artifacts --repo $REPO --pattern $PATTERN $TAG
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PATTERN: '*'
          TAG: ${{ github.ref_name }}
      - run: ls | xargs -I {} gh attestation verify --repo $REPO {}
        working-directory: artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
