name: govulncheck

on:
  schedule:
    - cron: '1 1 * * 1'
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: {}

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: golang/govulncheck-action@v1
        with:
          go-version-file: 'go.mod'
          go-package: ./...
